import 'bootstrap/dist/css/bootstrap.css'
import '../styles/globals.css'

import type { AppProps } from 'next/app'
import Head from 'next/head'

function ZaalvoetbalbazenApp({ Component, pageProps }: AppProps) {
  return <>
    <Head>
      <title>Zaalvoetbalbazen</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Component {...pageProps} />
  </>
}

export default ZaalvoetbalbazenApp
